version: 0.2

env:
  exported-variables:
    - TF_OUTPUT_URL
  variables:
    TF_VERSION: "1.5.3"

phases:

  install:
    commands:
      - cd /usr/bin
      - curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip -o terraform.zip
      - terraform --version

  build:
    commands:
      # Init terraform, run the plan command and output the plan as tfplan and txt files.
      - cd ${CODEBUILD_SRC_DIR}/tf
      - terraform init -no-color
      - terraform plan -out=tfplan_commitid_${CODEBUILD_RESOLVED_SOURCE_VERSION}_pipelineid_${PIPELINE_EXECUTION_ID} 
      - terraform show -no-color tfplan_commitid_${CODEBUILD_RESOLVED_SOURCE_VERSION}_pipelineid_${PIPELINE_EXECUTION_ID} > tfout_commitid_${CODEBUILD_RESOLVED_SOURCE_VERSION}_pipelineid_${PIPELINE_EXECUTION_ID}.txt
      - cp tfplan_commitid_${CODEBUILD_RESOLVED_SOURCE_VERSION}_pipelineid_${PIPELINE_EXECUTION_ID} ${CODEBUILD_SRC_DIR}/
      - aws s3 cp tfout_commitid_${CODEBUILD_RESOLVED_SOURCE_VERSION}_pipelineid_${PIPELINE_EXECUTION_ID}.txt s3://${ARTIFACTS_BUCKET}/tfout/tfout_commitid_${CODEBUILD_RESOLVED_SOURCE_VERSION}_pipelineid_${PIPELINE_EXECUTION_ID}.txt
      # We export a presigned URL for S3 to show in the approval prompt.
      - export TF_OUTPUT_URL=$(aws s3 presign s3://${ARTIFACTS_BUCKET}/tfout/tfout_commitid_${CODEBUILD_RESOLVED_SOURCE_VERSION}_pipelineid_${PIPELINE_EXECUTION_ID}.txt)
      # Stop the pipeline if no changes were detected:
      - output=$(cat tfout_commitid_${CODEBUILD_RESOLVED_SOURCE_VERSION}_pipelineid_${PIPELINE_EXECUTION_ID}.txt) && echo "$output" | grep -q "no changes" && aws codepipeline stop-pipeline-execution --no-abandon --pipeline-name ${PIPELINE_NAME} --pipeline-execution-id ${PIPELINE_EXECUTION_ID} --reason "No changes detected."



  post_build:
    commands:
      - echo "Terraform plan completed on `date`"

artifacts:
  files:
    - tfplan_commitid_${CODEBUILD_RESOLVED_SOURCE_VERSION}_pipelineid_${PIPELINE_EXECUTION_ID}
  name: TerraformPlanFile